security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Activer la connexion via formulaire
            form_login:
                login_path: login    # URL où se trouve ton formulaire
                check_path: login    # URL de vérification (souvent identique)
                username_parameter: _username  # par défaut
                password_parameter: _password
                default_target_path: /    # Redirection après connexion réussie

            logout:
                path: logout
                target: /login

    access_control:       
        - { path: ^/post, roles: ROLE_USER }
        

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
