name: CI/CD Symfony Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Installer PHP + Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: intl, pdo, pdo_mysql, zip

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # 3️⃣ Lancer les tests
      - name: Run PHPUnit
        run: |
          php bin/phpunit

      # 4️⃣ Déployer sur ton serveur
      - name: Deploy to production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/Flashlab
            git pull origin main
            php bin/console cache:clear --env=prod
